
services:

  happyr.serializer.metadata.annotation_reader:
    class: Happyr\SerializerBundle\Metadata\AnnotationReader
    public: false
    arguments:
      - []
      - '@annotation_reader'
      - "@happyr.serializer.property_access.attribute_extractor"

  happyr.serializer.metadata.metadata_provider:
    class: Happyr\SerializerBundle\Metadata\MetadataProvider
    public: false
    arguments:
      - ['@happyr.serializer.metadata.annotation_reader']

  happyr.serializer.property_access.attribute_extractor:
    class: Happyr\SerializerBundle\PropertyManager\AttributeExtractor
    public: false

  happyr.serializer.normalizer.metadata_aware:
    class: Happyr\SerializerBundle\Normalizer\MetadataAwareNormalizer
    arguments:
      - []
      - "@happyr.serializer.property_access.attribute_extractor"
      - "@happyr.serializer.normalizer.property_manager.name_converter"
    public: false
    tags:
      - { name: "serializer.normalizer", priority: -999 }

  happyr.serializer.denormalizer.metadata_aware:
    class: Happyr\SerializerBundle\Normalizer\MetadataAwareDenormalizer
    arguments: [[], "@happyr.serializer.normalizer.property_manager.name_converter"]
    public: false
    tags:
      - { name: "serializer.normalizer", priority: -999 }

  happyr.serializer.normalizer.property_manager.name_converter:
    class: Happyr\SerializerBundle\PropertyManager\PropertyNameConverter
    arguments: [~]
    public: false